### ISSUE TITLE
Необходимо исправить вывод строк с одинаковыми датами в ДЗ forms/steps

### ISSUE THREAD

**Issue by NataliaGracheva** [NataliaGracheva/ra-homeworks#1]
Через создание нового массива, в котором значения km  с одинаковыми датами складываются,  не получается. 
https://github.com/NataliaGracheva/ra-homeworks/blob/c2313916236341a17cdb3915938ef3514f3fd42d/forms/steps/src/components/StepCounter.jsx#L10
Можно ли как-то проще это сделать?

**Comment by coursar** [comment]
См #2
