### ISSUE TITLE
Не работает фильтр в задании redux/filter

### ISSUE THREAD

**Issue by NataliaGracheva** [NataliaGracheva/ra-homeworks#20]
[serviceList.js](https://github.com/NataliaGracheva/ra-homeworks/blob/cddf17abf5d31aa7db474afe4b2651ea7fd3ca5c/redux/filter/frontend/src/reducers/serviceList.js#L25)
Не работает сам фильтр и кнопка отмены тоже не работает
Очень прошу помочь

**Comment by coursar** [comment]
Если вопрос закрыт, то issue надо закрывать.
